= Compiler et construire ses applications avec maven
Jean-Michel Bruel <jbruel@gmail.com>
v22.1, 2022-09-04 : BUT 2 version
//v1, 2022-02-20 : Initial draft
:icons: font
:diagrams: .
:experimental:
:classroom-link: https://classroom.github.com/a/gWXnQmIT
:imagesdir: images

// Useful definitions
:eclipse: http://www.eclipse.org[Eclipse]
:intellij: https://www.jetbrains.com/idea/[IntelliJ]
:maven: http://maven.apache.org/[Maven]
:vscode: https://code.visualstudio.com/[VS Code]

// Specific to GitHub
ifdef::env-github[]
:toc:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:icongit: Git
endif::[]

//---------------------------------------------------------------

Ce TP vise à être capable de compiler un fichier Java sans être dépendant de son IDE favori.
Cela permet :

- d'être indépendant de tout IDE
- de faire construire l'application de manière automatique (c'est pour plus tard, mais c'est ce qu'on appelle l'intégration continue)

== Mise en place

WARNING: Les illustrations utilisent {vscode}, mais peu importe que vous utilisiez un autre IDE comme {eclipse} ou {intellij}, il vous suffit d'adapter à votre IDE (qu'il vous faut apprendre à connaître).

Le plus simple pour réaliser ce TP est d'utiliser gitpod : rajoutez `gitpod.io/#` devant l'URL de votre dépôt ou cliquez sur le bouton Gitpod si vous en avez un qui s'affiche.
Mais nous vous conseillons d'utiliser plutôt votre IDE personnel, pour vérifier que votre machine est bien configurer pour l'utiliser pour tous les TPs à suivre (et pouvoir travailler même sans réseau!).

.Pour les utilisateurs des machines IUT (merci à Rémy Guibert)
[WARNING]
====
Pour ceux qui veulent lancer les commandes {maven} sur leur machine :

. Placez vous dans le répertoire cloné (par exemple `r3-04-td1-maven-Dupont`)
. Ouvrez une invite de commande Windows (CMD) dans ce répertoire
. Tapez la commande :
+
....
set JAVA_HOME=C:\Program Files\Java\jdk-17.0.1
....
+
. Vous pouvez maintenant taper les commandes {maven}

Vous pouvez aussi importer dans eclipse votre projet maven puis faire exécuter à eclipse votre `pom.xml` (menu:Run as...[Maven]).
====

== C'est parti

=== Documentation du projet

Pour utiliser le projet vous devez suivre les instructions suivantes :

. Tout d'abord, nettoyez le projet Maven avec la commande :
+
....
mvn clean
....

. Ensuite, pour compiler l'application utilisez la commande :
+
....
mvn compile
....

. Lancez la fabrication d'une version exécutable avec la commande :
+
....
mvn package
....
+
NOTE: Lorsque vous exécutez `mvn package`, la javadoc se génère automatiquement. Vous la trouverez sous forme de site dans le dossier target/apidocs ET sous forme de jar dans le dossier target (tp_qualite-1.0-javadoc.jar).

. Pour générer la Javadoc du projet manuellement, vous pouvez exécuter la commande :
+
....
mvn javadoc:javadoc
....
+
NOTE: Lors de l'exécution de `mvn javadoc:javadoc`, la javadoc se générera dans le dossier target/site/apidocs.

. Pour tester la version exécutable, exécutez la commande :
+
....
java -jar target/tp_qualite-1.0.jar
....

== Améliorations

. Reprenez un de vos exercices précédents et mettez les sources dans `src/java`.
. Ajustez éventuellement le `pom.xml` pour que les étapes précédentes produisent les résultats escomptés. Pensez à vérifier que votre fichier .jar est exécutable. Que devez-vous corriger dans votre pom.xml ? Quelle est la commande pour le lancer ?
. Ajoutez les commentaires vus en dev.
. Cherchez dans la documentation {maven} les commandes permettant de générer une documentation javadoc, et les adaptions à faire sur votre projet (et éventuellement `pom.xml`) afin que {maven} génère la documentation automatiquement pour vous.
. Documentez votre projet: remplacez le contenu de ce fichier README.doc par les instructions de compilation, de documentation et de lancement de votre projet. 

== Consignes et rendus

Pour ce TP, il vous faudra simplement rendre le projet complet (`src`) ainsi que la dernière version du fichier `pom.xml` sur votre dépôt et la javadoc de votre code.

