= Compiler et construire ses applications avec maven
Jean-Michel Bruel <jbruel@gmail.com>
v22.1, 2022-09-04 : BUT 2 version
//v1, 2022-02-20 : Initial draft
:icons: font
:diagrams: .
:experimental:
:classroom-link: https://classroom.github.com/a/gWXnQmIT
:imagesdir: images

// Useful definitions
:eclipse: http://www.eclipse.org[Eclipse]
:intellij: https://www.jetbrains.com/idea/[IntelliJ]
:maven: http://maven.apache.org/[Maven]
:vscode: https://code.visualstudio.com/[VS Code]

// Specific to GitHub
ifdef::env-github[]
:toc:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:icongit: Git
endif::[]

//---------------------------------------------------------------

Binome : 

- Dylan Latapie 3B
- Maël Carrié 3B

Lien vers l'autre dépot : https://github.com/IUT-Blagnac/r3-04-qualite-tp1-MaelCarrie

== Prérequis

- Java 17 (jdk-17.0.1)
- Maven

Vous pouvez utiliser VSCode ou tout IDE compatible mais le plus simple pour utiliser ce projet est d'utiliser gitpod : rajoutez `gitpod.io/#` devant l'URL de votre dépôt ou cliquez sur le bouton Gitpod si vous en avez un qui s'affiche.

== Documentation du projet

Pour utiliser le projet vous devez suivre les instructions suivantes :

. Tout d'abord, nettoyez le projet Maven avec la commande :
+
....
mvn clean
....

. Ensuite, pour compiler l'application utilisez la commande :
+
....
mvn compile
....

. Lancez la fabrication d'une version exécutable avec la commande :
+
....
mvn package
....
+
NOTE: Lorsque vous exécutez `mvn package`, la javadoc se génère automatiquement. Vous la trouverez sous forme de site dans le dossier target/apidocs ET sous forme de jar dans le dossier target (tp_qualite-1.0-javadoc.jar).

. Pour générer la Javadoc du projet manuellement, vous pouvez exécuter la commande :
+
....
mvn javadoc:javadoc
....
+
NOTE: Lors de l'exécution de `mvn javadoc:javadoc`, la javadoc se générera dans le dossier target/site/apidocs.

. Pour tester la version exécutable, exécutez la commande :
+
....
java -jar target/tp_qualite-1.0.jar
....
